# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    working_directory: "/go/src/helmsman"
    docker:
      - image: praqma/helmsman-test
    steps:
      - checkout
      - run:
          name: Build helmsman
          command: |
            echo "building ..."
            export GOOS=linux
            make build

  test:
    working_directory: "/go/src/helmsman"
    docker:
      - image: praqma/helmsman-test
    steps:
      - checkout
      - run:
          name: Unit test helmsman
          command: |
            echo "running tests ..."
            export GOOS=linux
            make test
  release:
    docker:
      - image: goreleaser/goreleaser
        entrypoint: /bin/bash
    working_directory: "/go/src/github.com/Praqma/helmsman"
    steps:
      - run:
          name: install git
          command: apk update && apk add --no-cache git dep openssh
      - checkout
      - run:
          name: release
          command: |
            dep ensure
            goreleaser release --release-notes release-notes.md

  docker-release:
    working_directory: "/tmp/go/src/helmsman"
    machine: true
    steps:
      - checkout
      - run:
          name: build docker images and push them to dockerhub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t praqma/helmsman:$CIRCLE_TAG-helm-v2.16.7 --build-arg HELM_VERSION=v2.16.7 --build-arg HELM_DIFF_VERSION=master -f dockerfile/dockerfile --no-cache .
            docker push praqma/helmsman:$CIRCLE_TAG-helm-v2.16.7
            docker build -t praqma/helmsman:$CIRCLE_TAG-helm-v2.15.2 --build-arg HELM_VERSION=v2.15.2 --build-arg HELM_DIFF_VERSION=master -f dockerfile/dockerfile --no-cache .
            docker push praqma/helmsman:$CIRCLE_TAG-helm-v2.15.2

      - run:
          name: build docker test images and push them to dockerhub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t praqma/helmsman-test:latest test_files/. --no-cache
            docker push praqma/helmsman-test:latest

workflows:
  version: 2
  build-test-push-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - docker-release:
          requires:
            - release
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
